### ISSUE TITLE
Sum tree find occasionally causes error on find()

### ISSUE THREAD

**Issue by mbecker12** [mbecker12/surface-rl-decoder#59]
```Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marvin/Projects/surface-rl-decoder/src/distributed/io.py", line 223, in io_replay_memory
    transitions, memory_weights, indices, priorities = replay_memory.sample(
  File "/home/marvin/Projects/surface-rl-decoder/src/distributed/prioritized_replay_memory.py", line 85, in sample
    data, priority, index = self.tree.find(rand)
  File "/home/marvin/Projects/surface-rl-decoder/src/distributed/sum_tree.py", line 85, in find
    return self._find(value, 0)
  File "/home/marvin/Projects/surface-rl-decoder/src/distributed/sum_tree.py", line 102, in _find
    return self._find(value - left, 2 * (index + 1))
  File "/home/marvin/Projects/surface-rl-decoder/src/distributed/sum_tree.py", line 102, in _find
    return self._find(value - left, 2 * (index + 1))
  File "/home/marvin/Projects/surface-rl-decoder/src/distributed/sum_tree.py", line 102, in _find
    return self._find(value - left, 2 * (index + 1))
  [Previous line repeated 7 more times]
  File "/home/marvin/Projects/surface-rl-decoder/src/distributed/sum_tree.py", line 92, in _find
    self.data[index - (2 ** (self.tree_level - 1) - 1)],
IndexError: list index out of range```

**Comment by mbecker12** [comment]
Could have been caused by insufficient error handling in the sample function for the line `weights = [i / weights_max for i in weights]`; need to account for the case that `weights_max = 0`. This was implemented
