### ISSUE TITLE
Edit logging

### ISSUE THREAD

**Issue by mbecker12** [mbecker12/surface-rl-decoder#78]
Looking back at old runs, the logs seem incomprehensible.

We might want additional info on transfer of network parameter across processes (lower required verbosity level for received/sent network parameters)

We need to check the impact of some warning messages:
- [ ] Caught NoneType ... in learner, when performing q learning step
- [ ] Faulty sampling from sum tree in IO module

**Comment by mbecker12** [comment]
```
ERROR:learner:Caught exception in learning step
ERROR:learner:Traceback (most recent call last):
  File "/surface-rl-decoder/src/distributed/learner.py", line 210, in learner
    indices, priorities = perform_q_learning_step(
  File "/surface-rl-decoder/src/distributed/learner_util.py", line 136, in perform_q_learning_step
    ) = data_to_batch(input_data, device, batch_size)
  File "/surface-rl-decoder/src/distributed/learner_util.py", line 74, in data_to_batch
    list_state, list_action, list_reward, list_next_state, list_terminal = zip(*batch)
TypeError: 'NoneType' object is not iterable
```
This suggests that one element in `batch` is None, but not that batch itself is None; this would throw another error

**Comment by mbecker12** [comment]
Secondly, the custom warning message in the IO module:
```
Caught AssertionError while trying to sample from replay memory. Skipping to new sample.
```
One might want to replace that with a time-limited while loop instead of printing the warning all the time

**Comment by mbecker12** [comment]
Also, change time_ms() to time() since tensorboard seems to handle time in seconds at least a slight bit better....

**Comment by mbecker12** [comment]
The issue of the second error (while sampling from replay memory) could actually be correlated to numerical issues when accidentally saving a one-element np.ndarray to the tree as a value, where it is expected to be a python native float

**Comment by mbecker12** [comment]
Also, set env variable CONFIG_ENV_SIZE=5 in github action tests to guarantee tests to function

**Comment by mbecker12** [comment]
Seems as though the second error caused the first error by sampling faulty items from the sum tree.
Can't reproduce the above errors anymore.
Also, did some changes to how errors in PER sampling are tracked and logged
